name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: std (windows)
            os: windows-2022
            target: x86_64-pc-windows-msvc
            args: ""
            run_tests: true
          - name: std (macos)
            os: macos-latest
            target: x86_64-apple-darwin
            args: ""
            run_tests: true
          - name: std (linux)
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            args: ""
            run_tests: true
          - name: no_std (thumbv7em)
            os: ubuntu-latest
            target: thumbv7em-none-eabi
            args: "--no-default-features"
            run_tests: false
          - name: no_std (riscv32 + portable-atomic)
            os: ubuntu-latest
            target: riscv32imc-unknown-none-elf
            args: "--no-default-features --features portable-atomic,portable-atomic/unsafe-assume-single-core"
            run_tests: false

    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} ${{ matrix.args }}

      - name: Test
        if: matrix.run_tests
        run: cargo test --target ${{ matrix.target }}
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --all-targets --all-features -- -D warnings
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --lcov --output-path target/lcov.info
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ratatui/kasuari
          fail_ci_if_error: false
